version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_database_dev

  front:
    image: boilerplate/django
    container_name: front
    command: yarn serve
    volumes:
      - ./:/usr/src/app/

  app:
    build: ./
    image: boilerplate/django
    container_name: app
    command: python manage.py runserver --settings=conf.settings.development 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - front
      
volumes:
  postgres_data:
